backtest_end_date: '2023-01-01'
backtest_start_date: '2022-01-01'
mean_reversion_threshold: 1.5
mean_reversion_window: 50
momentum_long_window: 50
momentum_short_window: 20
momentum_threshold: 0.1
notification_interval: 60
reliability:

  experiment_period: 800
  preferred_period: 60
volatility_atr_multiplier: 1.5
volatility_atr_window: 14
volatility_breakout_window: 20
