name: Market Signals Telegram Bot

on:
  schedule:
    # Run at 30 minutes after NYSE close (4:30 PM ET)
    # This is 21:30 UTC during standard time, 20:30 UTC during daylight saving
    - cron: '30 20 * * 1-5'  # During daylight saving
    - cron: '30 21 * * 1-5'  # During standard time
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  run-market-signals:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run market signals bot
      env:
        TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
      run: |
        python main.py --daily-run --force
    
    - name: Upload generated charts as artifacts
      uses: actions/upload-artifact@v4  # Updated from v3 to v4
      with:
        name: signal-charts
        path: |
          *.png
          charts/*.png
        if-no-files-found: ignore